stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:8-alpine
  script:
    - NODE_ENV=development yarn
    - NODE_ENV=production yarn build
  artifacts:
    paths:
      - build

build:latest:
  stage: build
  image: docker:git
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
    - dev

deploy:staging:
  image: alpine
  stage: deploy
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh urbica@gulag.urbica.co 'bash -s' < deploy-staging.sh
  environment:
    name: staging
    url: http://gulag.urbica.co
  only:
    - dev

deploy:production:
  image: alpine
  stage: deploy
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh docker@gulagmap.ru 'bash -s' < deploy-production.sh
  environment:
    name: production
    url: http://gulagmap.ru
  only:
    - master